### ISSUE TITLE
Proposal: add support for custom time format layouts

### ISSUE THREAD

**Issue by rotemhoresh** [Oudwins/zog#21]
I have noticed that the time coercer is using the `time.RFC3339` format layout when the to-be-`time.Time` is a `string`.
So, if in my app I use the layout `2006-01-02` (the format that the HTML date input uses), I'll need to add a `PreTransform`, e.g.:

```go
z.Time().PreTransform(func(data any, ctx primitives.ParseCtx) (out any, err error) {
    str, ok := data.(string)
    if !ok {
        return nil, errors.New("not a string")
    }
    return time.Parse("2006-01-02", str)
})
```

Now, although it's not a big deal, I do think it would be nicer to be able to just specify a format (maybe by adding a `format` field to the `timeProcessor` struct, and a `Format` method to modify it).

I'd love to hear what you think of this proposal, and if you think it's a good idea but don't have the time (or the will :D), I'd be happy to create a PR.

**Comment by rotemhoresh** [comment]
Hey!

The second - being able to specify custom format in the schema itself, instead of using a `PreTransform`.
For example:

```go
z.Time().Format("2006-01-02")
```

**Comment by Oudwins** [comment]
Sorry I think i didnt explain myself very well. 

I understand what you are asking. My question is: 

Is there a reason why you think it's not good enough to be able to change the coercer? 

I.e if you change the time coercer you can make zog coerce time strings into your desired format by default. I'm on mobile otherwise I would give an example here but you can look at the "overriding defaults" section of the readme

**Comment by rotemhoresh** [comment]
I just thought it would be nicer to be able to specify format via the schema (declarative, less code, etc.).

But:
-  I have read that the format you chose (`time.RFC3339`), is the most common one - RFC 3339 accounts for 57% of all explicitly specified time formats (https://go.dev/issue/52746) and it is used implicitly by the `Time.(Marshal|Unmarshal)(Text|JSON)` methods (https://cs.opensource.google/go/go/+/refs/tags/go1.23.1:src/time/format_rfc3339.go;l=11;bpv=0). (I guess you know that, and that is the reason you chose it).
- The use case of changing the format, is only for strings, and most won't need to change format (because it is the most common one).

So, I can understand why you think it is probably better to leave things as they are.

If you do think so, and don't intend to add a `Format` method (which, again, I understand), feel free to close this issue 👍.

**Comment by Oudwins** [comment]
Hey! @rotemhoresh. No, no, pkease i think the idea is interesting. No worries on my end, I just wanted to better understand where you were coming from. Actually I do agree that it would be nice to be able to specify the format in the schema. 

However, it's not as simple as adding it to the timeprocessor. Since this is coercion from string to time.Time struct. This is handled by the time coercer not the timeProcessor and I do want to keep that separate because in the future I would like to allow a "strict" parsing flag that will disable coercion which is enabled by default. 

So implementing this would probably mean that we need to do a breaking change on the coercer interface to pass it some kind of arguments. Or, alternatively, polute the Parsing Context with that information (which I dislike). 


That is why I am trying to understand how important is the orgonomics of specifying the format in the schema.

**Comment by rotemhoresh** [comment]
I don't feel that I'm qualified to say how important this is, as I haven't used `Zog` for too long.

But, for example, when using `Zog` for parsing HTTP requests (which I think you consider a common use case, because you've created `zhttp`), you'll probably need to parse times as strings (from form submissions for example).

I don't know how important is the use case of using it in web servers, but in the HTML `input`, there are at least 5 input types of time/date (although I believe one of them is in a format not supported by the `time` package).

I can't tell how important this is, but in the use cases I got to use `Zog`, I needed to parse the time as a string.

**Comment by Oudwins** [comment]
Let me give it some thought then and decided how to move forward with this. Thank you for bring it up!

**Comment by Oudwins** [comment]
@rotemhoresh Quick heads up. Sorry for taking so long to decide how to best implement it, I had a lot of other things on my plate. I'll implement this hopefully this week. The final syntax will look like this:

```go
schema := z.Time(z.Time.Format(time.RFC...))
```

There will also be a format func that will allow you to implement custom formatting:
```go
schema := z.Time(z.Time.FormatFunc(....))
```

Under the hood. This will be implemented as a custom coercer attached to the time processor

**Comment by rotemhoresh** [comment]
Hi!

Great to hear, looking forward 🙃

**Comment by Oudwins** [comment]
@rotemhoresh closing this for now. as #48 addreses it. Once you have an opportunity to try it let me know if the API feels nice! Feature should be out with a new release around tomorrow
